name: Extension Release

on:
  push:
    branches:
      - 'main'
    paths:
      - 'extensions/**/updates.xml'

permissions:
  contents: write

jobs:
  # https://github.com/tj-actions/changed-files/blob/main/.github/workflows/matrix-example.yml
  changed-files:
    name: Get all changed extensions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all changed xml files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          matrix: true
          files: |
            extensions/**/updates.xml

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

#      - name: Define Extensions
#        id: extensions
#        run: |
#          IFS='|' read -r -a extensions <<< "${ALL_CHANGED_FILES}"
#          echo 'colors=${extensions[@]}' >> "$GITHUB_OUTPUT"

  build:
    name: Package Extension
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix:
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo files
        run: |
          echo ${{ matrix.files }}

      - name: Get Plugin Path
        run: |
          echo "PLUGIN_PATH=`expr "${{ matrix.files }}" : '\(.*\)\/updates.xml'`" >> $GITHUB_ENV

      # Get vars from updates.xml
      - name: Get Version
        id: getversion
        uses: mavrosxristoforos/get-xml-info@2.0
        with:
          xml-file: ${{ matrix.files }}
          xpath: '//update[1]/version'

      - name: Get Plugin Element
        id: getplugin
        uses: mavrosxristoforos/get-xml-info@2.0
        with:
          xml-file: ${{ matrix.files }}
          xpath: '//update[1]/element'

      - name: Get Plugin Name
        id: getpluginname
        uses: mavrosxristoforos/get-xml-info@2.0
        with:
          xml-file: ${{ matrix.files }}
          xpath: '//update[1]/name'

      - name: Set Variables
        id: vars
        run: |
          echo ${{ steps.getversion.outputs.info }}
          echo ${{ steps.getplugin.outputs.info }}
          echo "plugin=${{ steps.getplugin.outputs.info }}" >> "$GITHUB_OUTPUT"
          echo "plugin_name=${{ steps.getpluginname.outputs.info }}" >> "$GITHUB_OUTPUT"
          path_tmp=${{ env.PLUGIN_PATH }}
          echo "plugin_path=${path_tmp// /\ }" >> "$GITHUB_OUTPUT"
          echo "version=${{ steps.getversion.outputs.info }}" >> "$GITHUB_OUTPUT"
          echo "package_name=${{ format('{0}-{1}.zip', steps.getplugin.outputs.info, steps.getversion.outputs.info) }}" >> "$GITHUB_OUTPUT"
          echo "package_path=${{ format('{2}/{0}-{1}.zip', steps.getplugin.outputs.info, steps.getversion.outputs.info, env.PLUGIN_PATH) }}" >> "$GITHUB_OUTPUT"

      - name: Composer Install
        if: ${{ startsWith(steps.vars.outputs.plugin, 'com_') }}
        uses: php-actions/composer@v6
        with:
          container_workdir: "/app/${{steps.vars.outputs.plugin_path}}/site"
          interaction: no

      # Build Extension ZIP
      - name: Build Extension ZIP
        run: |
          cd "${{steps.vars.outputs.plugin_path}}"
          zip -r ${{steps.vars.outputs.package_name}} . -x updates.xml

      # Create Tag
      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ steps.vars.outputs.plugin }}/
          custom_tag: ${{ steps.vars.outputs.version }}

      # Create Release
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: ${{ steps.tag.outputs.new_tag }}
          name: ${{ steps.vars.outputs.plugin_name }} ${{ steps.vars.outputs.version }} (${{ steps.vars.outputs.plugin }})
          draft: false
          prerelease: false
          files: ${{ steps.vars.outputs.package_path }}
          generate_release_notes: true

      # S3 upload
      - name: S3 Upload - ZIP
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-west-1
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: ${{ steps.vars.outputs.package_path }}
          destination-dir: ${{ steps.vars.outputs.plugin }}
          bucket-root: /
          public: true

      - name: S3 Upload - XML
        uses: hkusu/s3-upload-action@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-west-1
          aws-bucket: ${{ secrets.AWS_BUCKET }}
          file-path: ${{ matrix.files }}
          destination-dir: ${{ steps.vars.outputs.plugin }}
          bucket-root: updates
          public: true
