name: Extension Release

on:
  push:
    branches:
      - 'main'
    paths:
      - 'extensions/**/updates.xml'

permissions:
  contents: write

jobs:
  # https://github.com/tj-actions/changed-files/blob/main/.github/workflows/matrix-example.yml
  changed-files:
    name: Get all changed extensions
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.changed-files.outputs.all_changed_files }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get all changed xml files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          matrix: true
          files: |
            extensions/**/updates.xml

      - name: List all changed files
        run: echo '${{ steps.changed-files.outputs.all_changed_files }}'

#      - name: Define Extensions
#        id: extensions
#        run: |
#          IFS='|' read -r -a extensions <<< "${ALL_CHANGED_FILES}"
#          echo 'colors=${extensions[@]}' >> "$GITHUB_OUTPUT"

  build:
    name: Package Extension
    runs-on: ubuntu-latest
    needs: [changed-files]
    strategy:
      matrix:
        files: ${{ fromJSON(needs.changed-files.outputs.matrix) }}
      max-parallel: 4
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo files
        run: |
          echo ${{ matrix.files }}

#      - name: Get Plugin Path
#        run: |
#          echo "PLUGIN_PATH=`expr "${{ matrix.files }}" : '\(.*\)\/updates.xml'`" >> $GITHUB_ENV

      # Get vars from updates.xml
      - name: Get Version
        id: getversion
        uses: mavrosxristoforos/get-xml-info@2.0
        with:
          xml-file: ${{ matrix.files }}
          xpath: '//update[1]/version'

      - name: Get Plugin Element
        id: getplugin
        uses: mavrosxristoforos/get-xml-info@2.0
        with:
          xml-file: ${{ matrix.files }}
          xpath: '//update[1]/element'

      - name: Get Plugin Name
        id: getpluginname
        uses: mavrosxristoforos/get-xml-info@2.0
        with:
          xml-file: ${{ matrix.files }}
          xpath: '//update[1]/name'

      - name: Set Variables
        id: vars
        run: |
          echo ${{ steps.getversion.outputs.info }}
          echo ${{ steps.getplugin.outputs.info }}
          echo "plugin=${{ steps.getplugin.outputs.info" >> "$GITHUB_OUTPUT"
          echo "plugin_name=${{ steps.getpluginname.outputs.info" >> "$GITHUB_OUTPUT"
          echo "plugin_path=`expr "${{ matrix.files }}" : '\(.*\)\/updates.xml'`" >> "$GITHUB_OUTPUT"
          echo "version=${{ steps.getversion.outputs.info" >> "$GITHUB_OUTPUT"
          echo "package_name=`expr "${{ steps.getplugin.outputs.info }}-${{ steps.getversion.outputs.info }}.zip"`" >> "$GITHUB_OUTPUT"
          echo "package_path=`expr "./${{ steps.getplugin.outputs.info }}-${{ steps.getversion.outputs.info }}.zip"`" >> "$GITHUB_OUTPUT"

      # Build Extension ZIP
      - name: Build Extension ZIP
        run: |
          zip -r ${{steps.vars.outputs.package_name}} ${{steps.vars.outputs.plugin_path}} -x "${{steps.vars.outputs.plugin_path}}/updates.xml"

      # Create Tag
      - name: Bump version and push tag
        id: tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ${{ steps.vars.outputs.plugin }}/
          custom_tag: ${{ steps.vars.outputs.version }}

      # Create Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.tag.outputs.new_tag }}
          release_name: ${{ steps.vars.outputs.plugin_name }} ${{ steps.vars.outputs.version }} (${{ steps.vars.outputs.plugin }})
          draft: false
          prerelease: false

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.vars.outputs.package_path }}
          asset_name: ${{ steps.vars.outputs.package_name
          asset_content_type: application/zip

    # - name: Run test suite
    #   run: composer run-script test
